'''
Report Generator Module
Saves tactical analysis and counter-strategy to a readable report file.
'''

import os
from datetime import datetime


def generate_report(situation, counter_strategy, output_dir='data/reports'):
    '''
    Save the analysis to a timestamped text report.

    Args:
        situation: the opponent situation summary
        counter_strategy: the generated counter-strategy text
        output_dir: where to save the report

    Returns:
        Path to the saved report file.
    '''
    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = 'tactical_report_' + timestamp + '.txt'
    filepath = os.path.join(output_dir, filename)

    line = '=' * 60
    dash = '-' * 60
    now_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    lines = []
    lines.append(line)
    lines.append('FOOTBALL TACTICAL AI - ANALYSIS REPORT')
    lines.append(line)
    lines.append('')
    lines.append('Generated: ' + now_str)
    lines.append('')
    lines.append('OPPONENT SITUATION')
    lines.append(dash)
    lines.append(situation)
    lines.append('')
    lines.append('RECOMMENDED COUNTER-STRATEGY')
    lines.append(dash)
    lines.append(counter_strategy)
    lines.append('')
    lines.append(line)
    lines.append('Generated by Football Tactical AI')

    report = '\n'.join(lines)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)

    print('Report saved to: ' + filepath)
    return filepath
